# Generated by Django 2.2.4 on 2019-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('latest_withdrawal', models.DateTimeField(auto_now=True)),
                ('daily_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
    ]
